server:
  port: 0

spring:
  application:
    name: user-service

  datasource:
    url: ${url}
    username: ${username_}
    password: ${password}
    driver-class-name: ${driver-class-name}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show_sql: true

  profiles:
    active: db