server:
  port: 8000

spring:
  application:
    name: apigateway-server
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**

        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin-service/**

        - id: deal-service
          uri: lb://DEAL-SERVICE
          predicates:
            - Path=/deal-service/**

        - id: authentication-server
          uri: lb://AUTHENTICATION-SERVER
          predicates:
            - Path=/authentication-server/**

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka